#!/usr/bin/ksh
num=1
until [ ${num} -gt 99 ]
do
	[ ${num} -ge 10 ] || mu_name=W_A_02_0${num}
	[ ${num} -ge 10 ] && mu_name=W_A_02_${num}
	uxadd mu mu=${mu_name} tnode=SF_A_02 label=\"Mass Management Unit\"
	num=` expr ${num} + 1`
done
