#! /bin/ksh 
###################################################################
#                 Backup traces from the server
###################################################################
# @(#) script sh
# @(#) created by  : Guy MULLER (Orsyp)
###################################################################
##
# revision : 1.4
# date     : 20090728
# author   : Zhibing Wang (Orsyp Inc)
# modifs   : adapted to work in the new case structure
##
##
# revision : 1.3
# date     : 20060329
# author   : Zhibing Wang (Orsyp Inc)
# modifs   : Replace the NFS with scp and ssh
##
##
# revision : 1.2
# date     : 20051003
# author   : Guy Muller (Orsyp Inc)
# modifs   : Redisign in order to use the nfs partition
##
# revision : 1.1
# date     : 20031218
# author   : Guy Muller (Orsyp Inc)
# modifs   : Standardization
##
# revision : 1.0
# date     : 20030925
# author   : Guy Muller (Orsyp Inc)
# modifs   : Packaging
##
# revision : 0.9
# date     : 20020907
# author   : Guy Muller (Orsyp Inc)
# modifs   : Creation

### Linux Configuration
#Fr_Cases_Dir_Base=/FR/DA/Incident\ Related\ Files
#Fr_Cases_Dir_Base=/FR/cases
fr_host=frsplda01
Fr_Cases_Dir_Base=/cases
Linux_Cases_Dir_Base=/cases

### Cygwin Configuration
#Fr_Cases_Dir_Base=/cygdrive/s/Incident\ Related\ Files
#Linux_Cases_Dir_Base=/cygdrive/u

# ----------------------------------------------- #
# MESSAGE FUNCTION
# ----------------------------------------------- #
UX_MESSAGE ()
{
loc_os=`uname`
case ${loc_os} in
        Linux )
                if [ ${UX_PRINT:-KO} = OK ]; then
                        print "$1"
                else
                        echo "$1"
                fi;;
        * ) echo "$1";;
esac
}

# ----------------------------------------------- #
# HELP FUNCTION
# ----------------------------------------------- #
HELP()
{
UX_MESSAGE "Syntax : $0 [-c <case number>]"
UX_MESSAGE "  # How to use :"
UX_MESSAGE "  # Case number : -c <case number>"
}

while getopts c: option
do
        case "${option}" in
                c )
                case_number_flag=on
                ux_case_number=${OPTARG}
                ;;
                *)
                HELP
                exit 1
                ;;
        esac
done
if [ $# -eq 0 ]; then
        HELP
	exit 1
fi

Case_Num=${ux_case_number}

ux_case_number_2dig=`echo ${Case_Num} | cut -c 1-2 `
ux_case_number_3dig=`echo ${Case_Num} | cut -c 1-3 `


su - da -c "ssh -t $fr_host [ -d "${Fr_Cases_Dir_Base}"/"${ux_case_number_2dig}xxx/${ux_case_number_3dig}xx/${Case_Num}" ]"
dir_exist=$?
if [ $dir_exist -eq 0 ];  then
	#Case_Path=`ls  -d ${Linux_Cases_Dir_Base}/*/${Case_Num}/trcs 2> /dev/null `
	Case_Path=`ls  -d ${Linux_Cases_Dir_Base}/*/${Case_Num} 2> /dev/null `
	if [ $? -eq 0 ] && [ `echo "${Case_Path}" | wc -l` -eq 1 ]; then
		chmod 777 ${Case_Path}/../*
		#for file_name in `ls "${Fr_Cases_Dir_Base}/${ux_case_number_2dig}xxx/${ux_case_number_3dig}xx/${Case_Num}"`
		file_list=`su - da -c "ssh -t frsplda01 echo "${Fr_Cases_Dir_Base}/${ux_case_number_2dig}xxx/${ux_case_number_3dig}xx/${Case_Num}"/\*" `
		echo $file_list
		file_list=`echo $file_list|sed 's/.$//'|sed 's/ \//,\//g'` #separate each file with a ,
		No_of_files=0
		i=1
		set -A file_array
		No_of_files=`echo ${file_list}|sed 's/,/\n/g'|wc -l`  #count how many files, by making each of them a separoate line
		while [ $i -le $No_of_files ]; do 
			file_array[$i]=`echo ${file_list}|cut -f${i} -d,` #cut out the  file name + path
			file_name=`eval basename \"${file_array[$i]}\"` #get the file name
			file_name1=`echo ${file_name}|sed 's/ /\\\\ /g'` # to add a \ in each space in the file name
			if [ ! -f "${Case_Path}/${file_name}" ]; then
				#cp -rv "${Fr_Cases_Dir_Base}/${ux_case_number_2dig}xxx/${ux_case_number_3dig}xx/${Case_Num}/${file_name}" ${Case_Path}
				su - da -c "scp -r \"$fr_host:${Fr_Cases_Dir_Base}/${ux_case_number_2dig}xxx/${ux_case_number_3dig}xx/${Case_Num}/${file_name1}\" ${Case_Path}"
				cp -rv "${Case_Path}/${file_name}" "${Case_Path}/work"
				chmod -R 777 "${Case_Path}/work"
				#su - da -c "scp -r $fr_host:"${Case_Path}/${file_name}" "${Case_Path}/../wrk""
			else
				echo "File ${file_name} already exists "
				echo "On FR :"
				su - da -c " ssh -t $fr_host ls -ld "${Fr_Cases_Dir_Base}/${ux_case_number_2dig}xxx/${ux_case_number_3dig}xx/${Case_Num}/${file_name}""
				echo "On  Linux :"
				ls -ld ${Case_Path}/${file_name}
			fi
			i=`expr $i + 1`
		done
	else
		echo "Directory for the case ${Case_Num} does not exists on Linux, create it first"
		exit 1
	fi
else
	echo "This case does not have any directory on the FR Side"
	exit 1
fi
