#! /bin/ksh
 
# ======================================================
#        UNIVERSE login routine
# ======================================================
 
U_BATCH_INIT ()

   { 

   set +a

   STATUS=1
   $UXEXE/uxjobinit "${S_USERNAME}" "${S_CODAUTEUR}" "${S_SOCIETE}" "${S_UG}" \
                    "${S_SIGCELL}"  "${S_CODEXP}"    "${S_UPROC}"   "${S_NUMPROC}"   "${$}"

   STATUS=$?

   if [ ${STATUS} -ne 0 ]
   then
     return ${STATUS} 
   fi

#------------------------------------------------------
# Building launching execution script name                   
#------------------------------------------------------
   if [ "${U_TMP_PATH:-UNDEFINED}" = "UNDEFINED" ]
   then
      s_numproc_file="/tmp/${S_ESPEXE}${S_NUMPROC}_${$}.uproc"
   else
     s_numproc_file="${U_TMP_PATH}/${S_ESPEXE}${S_NUMPROC}_${$}.uproc"
   fi

   if [ ! -s ${s_numproc_file} ]
   then
      return 1 
   fi


   chmod 0700 $s_numproc_file
   . $s_numproc_file 
   STATUS=$?

   unalias rm
   rm -f ${s_numproc_file}

   if [ ${STATUS} -ne 0 ]
   then
       return ${STATUS} 
   fi

#------------------------------------------------------
# Control if UPROC script exist, and control if script 
# is executable      
#------------------------------------------------------
 
   if [ ! -x  ${S_PATH_UPROC} ] 
   then 
      STATUS=255
   fi

   if [ ! -r  ${S_PATH_UPROC} ] 
   then 
      STATUS=255
   fi

   return ${STATUS}
   }
 
 
# ======================================================
#        Routine to execute customized client shell
# ======================================================
 
U_BATCH_CLIENT ()

   { 
# Uncomment the line below if you will to ignore the SIGTERM signal

#    trap ' '  15

   RESEXE=0
#------------------------------------------------------
#       Launching customized client init shell
#------------------------------------------------------

   if [ -x $UXMGR/U_ANTE_UPROC ]
   then
           unix_status=0
           alias exit=". $UXMGR/UNIX_STATUS "
           alias return=". $UXMGR/UNIX_STATUS "
        . $UXMGR/U_ANTE_UPROC 
           if [ ${unix_status} -ne 0 ]
           then
              MSGINITFAILED=`$UXEXE/uxgetmsg`
              echo ${MSGINITFAILED}
              $UXEXE/uxset msg "${MSGINITFAILED}"
           fi

# Comment the line below if you will that an abnormal return status of      
# U_ANTE_UPROC routine does not put the UPROC status to Incident

           RESEXE=${unix_status}      
           unalias exit
           unalias return  
   fi

   if [ ${RESEXE} -ne 0 ]
   then
       return ${RESEXE} 
   fi

#------------------------------------------------------
#       Launching UPROC script shell
#------------------------------------------------------
   if [ "${S_CMD_UPROC:-UNDEFINED}" = "UNDEFINED" ] 
   then
       return 1
   fi
 
   eval $S_CMD_UPROC 
   RESEXE=$?
   export RESEXE

#------------------------------------------------------
#       Launching client customized post UPROC routine 
#------------------------------------------------------
   if [ -x $UXMGR/U_POST_UPROC ]
   then
           $UXMGR/U_POST_UPROC 
           #<<<
           #VFE 29SEP2005 propagate U_POST_UPROC result
           RESEXE=$?
           #>>>

   fi
   return $RESEXE 
   }

# ======================================================
#       UNIVERSE technical end_of_job routine 
# ======================================================
 
U_BATCH_TERM ()

   { 
   times > "/tmp/${S_NUMPROC}_${$}.conso"
   Iscn=0
   while read BUFFER 
   do    
     let Iscn=Iscn+1
     if [ $Iscn -eq 2 ]
     then
        export STR_TIMES="$BUFFER" 
     fi 
   done   < "/tmp/${S_NUMPROC}_${$}.conso"
   rm  -f /tmp/${S_NUMPROC}_${$}.conso
   if [ -x $UXEXE/uxjobstatus ]
   then
      $UXEXE/uxjobstatus ${RESEXE}
      result=$?
      if [ $result -ne 2 ]
      then
         RESEXE=$result
      fi
   fi
   $UXEXE/uxjobend ${RESEXE}
   }
 
# ======================================================
#       Standard nut shell to execute UNIVERSE UPROC task      
#
# MAIN 
# ======================================================
 

export S_USERNAME="${1}"
export S_CODAUTEUR="${2}"
export S_SOCIETE="${3}"
export S_UG="${4}"
export S_SIGCELL="${5}"
export S_CODEXPMGR="${6}"
export S_UPROC="${7}"
export S_NUMPROC="${8}"
export PROCESS_MODE="BATCH"

export DQM_QUEUE="${5}"
if [ $# -eq 9 ]
then
   export DQM_NOEUD_ORIGINE=${9}
fi

  export UXMGR=`echo "${S_CODEXPMGR}" | cut -c 3- `
  export S_CODEXP=`echo "${S_CODEXPMGR}" | cut -c 1-2 `

# -> LOGIN UNIVERSE  
   . $UXMGR/uxsetenv
   export S_ESPEXE=`echo "${S_CODEXP}" | cut -c 2 `

U_BATCH_INIT
STATUT_INIT=$?

if [ ${STATUT_INIT} -eq 0 ]
then
   U_BATCH_CLIENT
   U_BATCH_TERM
   exit $RESEXE
else
   RESEXE=$STATUT_INIT
   U_BATCH_TERM
   exit $RESEXE
fi

 
