#! /bin/sh
###################################################################
#                 Backup traces from the server
###################################################################
# @(#) script sh
# @(#) created by  : Guy MULLER (Orsyp)
###################################################################
##
# revision : 1.2
# date     : 20051003
# author   : Guy Muller (Orsyp Inc)
# modifs   : Redisign in order to use the nfs partition
##
# revision : 1.1
# date     : 20031218
# author   : Guy Muller (Orsyp Inc)
# modifs   : Standardization
##
# revision : 1.0
# date     : 20030925
# author   : Guy Muller (Orsyp Inc)
# modifs   : Packaging
##
# revision : 0.9
# date     : 20020907
# author   : Guy Muller (Orsyp Inc)
# modifs   : Creation

### Linux Configuration
#Fr_Cases_Dir_Base=/FR/DA/Incident\ Related\ Files
Fr_Cases_Dir_Base=/FR/cases
Linux_Cases_Dir_Base=/cases

### Cygwin Configuration
#Fr_Cases_Dir_Base=/cygdrive/s/Incident\ Related\ Files
#Linux_Cases_Dir_Base=/cygdrive/u

# ----------------------------------------------- #
# MESSAGE FUNCTION
# ----------------------------------------------- #
UX_MESSAGE ()
{
loc_os=`uname`
case ${loc_os} in
        Linux )
                if [ ${UX_PRINT:-KO} = OK ]; then
                        print "$1"
                else
                        echo "$1"
                fi;;
        * ) echo "$1";;
esac
}

# ----------------------------------------------- #
# HELP FUNCTION
# ----------------------------------------------- #
HELP()
{
UX_MESSAGE "Syntax : $0 [-c <case number>]"
UX_MESSAGE "  # How to use :"
UX_MESSAGE "  # Case number : -c <case number>"
}

while getopts c: option
do
        case "${option}" in
                c )
                case_number_flag=on
                ux_case_number=${OPTARG}
                ;;
                *)
                HELP
                exit 1
                ;;
        esac
done
if [ $# -eq 0 ]; then
        HELP
	exit 1
fi

Case_Num=${ux_case_number}

ux_case_number_2dig=`echo ${Case_Num} | cut -c 1-2 `
ux_case_number_3dig=`echo ${Case_Num} | cut -c 1-3 `


if [ -d "${Fr_Cases_Dir_Base}/${ux_case_number_2dig}xxx/${ux_case_number_3dig}xx/${Case_Num}" ]
then
	Case_Path=`ls  -d ${Linux_Cases_Dir_Base}/*/${Case_Num}/trcs 2> /dev/null `
	if [ $? -eq 0 ] && [ `echo "${Case_Path}" | wc -l` -eq 1 ]
	then
		for file_name in `ls "${Fr_Cases_Dir_Base}/${ux_case_number_2dig}xxx/${ux_case_number_3dig}xx/${Case_Num}"`
		do
			if [ ! -f ${Case_Path}/${file_name} ]
			then
				cp -rv "${Fr_Cases_Dir_Base}/${ux_case_number_2dig}xxx/${ux_case_number_3dig}xx/${Case_Num}/${file_name}" ${Case_Path}
				cp -rv "${Case_Path}/${file_name}" "${Case_Path}/../wrk"
			else
				echo "File ${file_name} already exists "
				echo "On FR :"
				ls -ld "${Fr_Cases_Dir_Base}/${ux_case_number_2dig}xxx/${ux_case_number_3dig}xx/${Case_Num}/${file_name}"	
				echo "On  Linux :"
				ls -ld ${Case_Path}/${file_name}
			fi
		done
	else
		echo "Directory for the case ${Case_Num} does not exists on Linux, create it first"
		exit 1
	fi
else
	echo "This case does not have any directory on the FR Side"
	exit 1
fi
