#! /bin/ksh
# ========================================================
# ORSYP.Sa
#  ------------------------------------------------------
#  UniJob shutdown procedure
# ========================================================
#
echo "UniJob shutdown procedure"
#
. /apps/unijob110/unijob/casdlsup06_unijob/data/unienv.ksh

cd ${U_ROOT_DIR}/app/bin

#  ------------------------------------------------------
#  UniJob shutdown
#  ------------------------------------------------------
./unijob -stop
cd ${U_ROOT_DIR}/data
