#! /bin/ksh
# ========================================================
# ORSYP.Sa
#  ------------------------------------------------------
#  UniJob startup procedure
# ========================================================
#
echo "UniJob startup procedure"
#
. /apps/unijob110/unijob/casdlsup06_unijob/data/unienv.ksh

cd ${U_ROOT_DIR}/app/bin

#  ------------------------------------------------------
#  UniJob start-up
#  ------------------------------------------------------
${U_ROOT_DIR}/app/bin/unijob -start
